# action.yml
name: 'Testht36gsd6'
description: 'Temporary action for testing'
inputs:
  who-to:
    description: 'Who to'
    required: true
    default: 'me'
outputs:
  time: # id of output
    description: 'The time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to }}